export {is} from './type/is'
export {isArray} from './type/isArray'
export {isDate} from './type/isDate'
export {isRegExp} from './type/isRegExp'
export {isFunction} from './type/isFunction'
export {isObject} from './type/isObject'
export {propIs} from './type/propIs'
export {type} from './type/type'
